### ISSUE TITLE
Kernel unable to initialize skl_n88l25_s4567 audio

### ISSUE THREAD

**Issue by paulhart** [thesofproject/avs-topology-xml#17]
Hi, I'm using an HP G1 13 Chromebook (a Skylake device) and built-in audio is not working. I've attached several files as requested (some of the other ones I either don't know how to look for or gave garbage output).

[dmesg.txt](https://github.com/thesofproject/avs-topology-xml/files/11447080/dmesg.txt)
[snd_modules.txt](https://github.com/thesofproject/avs-topology-xml/files/11447083/snd_modules.txt)
[nhlt.log](https://github.com/thesofproject/avs-topology-xml/files/11447147/nhlt.log)

If there are additional items I can share, please let me know, I'm keen to get this up and running!

it's a `0x9d70` device and the kernel uname is `6.3.1-arch2-1 #1 SMP PREEMPT_DYNAMIC Wed, 10 May 2023 08:54:47 +0000 x86_64 GNU/Linux`

**Comment by crojewsk-intel** [comment]
Thanks for sharing your problem with us.

This issue is very similar to [Missing ssm4567 topology](https://github.com/thesofproject/avs-topology-xml/issues/4), that is, Skylake-based Chromebook configurations were left on v5.4 - we haven't up-rev'ed the skylake-driver (the driver responsible for audio functionality) there and installing more recent kernels will lead to problems. Those problems are mainly connected to the topology files - think of them as configuration files. These were not provided nor maintained officially for quite some time and thus did not age well.

However, there have been multiple efforts to ease the pain from both teams, Intel and Google alike. First, we decided to revisit the skylake-driver topologies and align them with ALSA-topology expectations. Aligned files can be found at [for-skylake-driver](https://github.com/thesofproject/avs-topology-xml/tree/for-skylake-driver) branch of this very repository. Checkout README of that branch to know which skylake-driver configurations were addressed and which were not.

Now, the main goal is the transition from the skylake-driver to the avs-driver which is basically a rewrite and comes along with new set of topology files and a [development kit (SDK)](https://github.com/intel-innersource/applications.audio.avsdk). In fact, SSM4567 topology file is here already - please see [ssm4567-tplg.xml](https://github.com/thesofproject/avs-topology-xml/blob/main/i2s/ssm4567-tplg.xml). It's just not distributed with Linux-distros yet. Hopefully that will change soon. Meanwhile, you can compile the file using avstplg tool that is part of avsdk.

**Comment by paulhart** [comment]
Thank you for such a clear and detailed response - I'll have a dig through the links and let you know how I get on.

**Comment by crojewsk-intel** [comment]
To be strict:

Your machine is equipped with four audio devices: DMIC, HDMI and I2C codec devices were transfer happens over I2S interface: nau8825 and ssm4567. All the topology files are upstreamed and available here. Compile them using first avstplg then alsatplg - the former understands the "AVS format" i.e.: how we, Intel model our streams, while the latter translates this to kernel-friendly format.

```
avstplg -c my_topology.xml -o my_topology.conf    # from Intel-specific to ALSA-UCM
alsatplg -c my_topology.conf -o my_topology.bin   # from ALSA-UCM to kernel-friendly
```
With that done, all that's left is to move these into `/lib/firmware/intel/avs/` directory. The `/lib/firmware` part may change depending on your distro.

**Comment by crojewsk-intel** [comment]
Closing as there have been no feedback and from developer team's perspective, relevant changes are already part of the kernel, avs-topology-xml and avsdk repos. If something new pops up, feel free to open a new ticket.
