### ISSUE TITLE
Missing ssm4567 topology

### ISSUE THREAD

**Issue by WeirdTreeThing** [thesofproject/avs-topology-xml#4]
A few skylake chromebooks need ssm4567 for speakers, could a topology be provided for it?

**Comment by crojewsk-intel** [comment]
Thanks for your ticket, @WeirdTreeThing. My suggestion would be to mention the name of the platform which utilizes such codec when opening an issue. I'm aware of Chell Chromebook device, perhaps you have something else.

Will check what we got in store - need something to test things out. If no test device is found, I'd appreciate you helping us validating the soon-to-be-proposed topology file.

**Comment by WeirdTreeThing** [comment]
Thanks for the help. I don't have a device with ssm4567 but I do know someone with a Chell that can validate the topology. Caroline and Sentry would also work if you have access to those.

**Comment by cujomalainey** [comment]
@crojewsk-intel we should be able to look it up in our systems, also coreboot should have the information in dt

**Comment by cujomalainey** [comment]
@crojewsk-intel looks like it is glados that was missed https://github.com/coreboot/coreboot/blob/55d47bd1bfb38aec5253529fded126e0c9238a89/src/mainboard/google/glados/variants/glados/overridetree.cb#L71

**Comment by crojewsk-intel** [comment]
Thanks for your input @cujomalainey. I finally got my hands on a Chell device. Unfortunately I was not able to boot it with kernel v5.4 - guess this is due to fact that it was not part of the v5.4/v5.10 uprev for the KBL, AML and APL based machines. The exact same problems which were present (and later addressed) for the mentioned platforms are manifesting on Chell. Frankly, this is somewhat reflected in [README](https://github.com/thesofproject/avs-topology-xml/tree/for-skylake-driver#supported-configurations) for the for-skylake-driver branch.

When using v4.19 kernel though, topology file loads fine and debug can begin.

@WeirdTreeThing I'll need a day or two to gather all required payloads from the machine and prepare avs-driver topology equivalent.

**Comment by crojewsk** [comment]
All the topologies for the avs-driver have been re-created from pre-v5.4 skylake-driver equivalents. Initial round of internal testings looks good.

The Chell did not make it to v5.4 up-rev so topologies it currently has deviate from upstream expectations (by upstream I mean any upstream kernel v5.4 and onward) - and that's why users get no audio with SKL-based Chromebooks when working with kernel newer than v4.19. The topology is simply incompatible. Made our job a bit harder compared to what I was initially expecting.

On Monday I'll be syncing with my friends from Google to do "semi" uprev for SKL-based devices. I'd like them tested by both teams before pushing anything to the repo.

**Comment by crojewsk-intel** [comment]
We still have points to cover, mainly related to improving user-experience. You see, currently names of some controls e.g.: volume control are not really user friendly. These are assigned by the ASoC framework automatically using "widget_name control_name" pattern. Instead of pretty "DSP Volume" we get: "ssp%d_fe DSP Volume". Choosing the best approach of how to improve things will take some time - review always does.

As my options in regard to testing are limited, I will kindly request help with testing things out - cannot guarantee anything yet. PRs:
- [i2s: max98357a: Topology updates](https://github.com/thesofproject/avs-topology-xml/pull/7)
- [i2s: Add SSM4567 topology](https://github.com/thesofproject/avs-topology-xml/pull/10)

are addressing problems found with max98357a topology as well as adding missing ssm4567. max98357a is mentioned here as it's part of Chell device just like ssm4567 is.

However, some shortcoming have been found within the kernel - topology update alone is insufficient. I'll be pushing these to upstream review soon, but since users you speak of are doing something that deviates from standard, I'm attaching changes proposed internally sooner than later.

[0001-ASoC-Intel-avs-ssm4567-Remove-nau8825-bits.patch](https://github.com/thesofproject/avs-topology-xml/files/10805093/0001-ASoC-Intel-avs-ssm4567-Remove-nau8825-bits.patch)
[0002-ASoC-Intel-avs-nau8825-Adjust-clock-control.patch](https://github.com/thesofproject/avs-topology-xml/files/10805099/0002-ASoC-Intel-avs-nau8825-Adjust-clock-control.patch)

**Comment by WeirdTreeThing** [comment]
Getting this error trying to load ssm4567 topology.
```
[    8.147198] avs_ssm4567 avs_ssm4567.1: ASoC: no complete control IO handler for DSP Volume type (g,p,i) 257:257:1 at 0x7f0
[    8.147208] avs_ssm4567 avs_ssm4567.1: ASoC: failed to load widget ssp%dp_fe
[    8.147212] avs_ssm4567 avs_ssm4567.1: ASoC: topology: could not load header: -22
```

**Comment by crojewsk-intel** [comment]
The exact same as described in the [parallel topic](https://github.com/thesofproject/avs-topology-xml/issues/5#issuecomment-1434583157) applies. You will need to backport [\[PATCH 0/4\] Add support for DSP volume controls](https://lore.kernel.org/all/20221214185500.3896902-1-amadeuszx.slawinski@linux.intel.com/) series.

Peakvol support is part of the avs-driver starting from v6.2 onward.

**Comment by WeirdTreeThing** [comment]
I built my kernel from [here](https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/?h=v6.2) which is 6.2 so I assumed it would have the DSP control patches but it seems like only linux-next has those patches.

**Comment by crojewsk-intel** [comment]
Well, you guys are trying to be "ahead of the curve". That's why taking even the latest-greatest stable may not suffice. Platforms such as Chell are officially supported on v4.19 ChromeOS.

We will keep supporting you guys though. I believe official switch to the avs-driver is just few weeks away.

**Comment by WeirdTreeThing** [comment]
With the DSP controls patches backported ssm4567 works great.

**Comment by crojewsk-intel** [comment]
Happy to hear and thanks for testing things out. Linux kernel patches are all either already merged into Mark's tree or posted on the alsa-devel mailing list. Link to the peakvol series can be found above. Link do the machine board fixes goes: [\[PATCH 0/5\] ASoC: Intel: avs: Machine board fixes](https://lore.kernel.org/alsa-devel/20230303134854.2277146-1-amadeuszx.slawinski@linux.intel.com).

**Comment by crojewsk-intel** [comment]
The relevant avs-topology-xml PR #10 has now been merged into branch: main.

**Comment by WeirdTreeThing** [comment]
Great, should be good to close the issue now.
